name: Publish Package to npmjs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: setup node to run 'corepack enable'
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: run 'corepack enable'
        run: corepack enable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bertonjulian'
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish Package to Github Packages  
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
      - uses: actions/setup-node@v4
        with:
          node-version-file: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@jberton'
      - run: yarn install --frozen-lockfile
      # publish to npmjs 
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
