name: Publish Packages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish Package to Github Packages  
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
      - uses: actions/setup-node@v4
        with:
          node-version-file: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@jberton'
      - run: yarn install --frozen-lockfile
      # publish to npmjs 
      - run: yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
